sudo: required
services:
  - docker

before_install:
  - docker build -t gerwel/docker-react-test:latest -f ./client/Dockerfile.dev ./client


script:
  - docker run -d -p 8081:3000 gerwel/docker-react-test 
  - docker ps



after_success:
  - docker build -t gerwel/multi-client:latest ./client
  - docker build -t gerwel/multi-server:latest ./server
  - docker build -t gerwel/multi-worker:latest ./worker
  - docker build -t gerwel/multi-nginx:latest ./nginx
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push gerwel/multi-client
  - docker push gerwel/multi-server
  - docker push gerwel/multi-worker
  - docker push gerwel/multi-nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: app-multi-container
  env: Appmulticontainer-env
  bucket_name: elasticbeanstalk-us-east-2-063353694214
  bucke_path: dockermulti 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: main